// Idempotent seed: wipes inventory, reviews, bookings, payments, notifications and the audit log,
// then re-creates them. Accounts are upserted (created or reset), never duplicated.
import 'dotenv/config';
import crypto from 'node:crypto';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import bcrypt from 'bcryptjs';
import mongoose from 'mongoose';
import { connectDb } from '../config/db.js';
import AuditLog from '../models/AuditLog.js';
import CancellationTemplate from '../models/CancellationTemplate.js';
import Config, { DEFAULT_COMMISSION_RATE } from '../models/Config.js';
import Offer from '../models/Offer.js';
import Photo from '../models/Photo.js';
import Adjustment from '../models/Adjustment.js';
import DailyStat from '../models/DailyStat.js';
import Event from '../models/Event.js';
import Statement from '../models/Statement.js';
import Ticket from '../models/Ticket.js';
import Booking from '../models/Booking.js';
import Flight from '../models/Flight.js';
import Hotel from '../models/Hotel.js';
import Notification from '../models/Notification.js';
import Payment from '../models/Payment.js';
import Review from '../models/Review.js';
import Service from '../models/Service.js';
import Supplier from '../models/Supplier.js';
import User from '../models/User.js';
import {
  generateAirlineSuppliers,
  generateDepartures,
  generateHotels,
  generateHotelSuppliers,
  generateReviews,
  generateServices,
} from './generate.js';
import { generateHistory, HISTORY_EMAIL_DOMAIN, seedSettlementHistory } from './history.js';
import { generateOffers } from './offers.js';
import { closeStatements, istPeriod, periodLabel, periodStart, shiftPeriod } from '../services/settlement.js';
import { DEFAULT_TEMPLATES } from '../services/templates.js';

// Admin and demo traveller passwords come only from server/.env (never committed): the same
// Atlas cluster backs the public site, so a password written in this file would be public.
const DEMO_USERS = [
  {
    name: 'Atlas Admin',
    email: process.env.SEED_ADMIN_EMAIL || 'admin@atlas.test',
    password: process.env.SEED_ADMIN_PASSWORD,
    role: 'admin',
  },
  {
    name: 'Priya Traveller',
    email: process.env.SEED_TRAVELLER_EMAIL || 'priya@atlas.test',
    password: process.env.SEED_TRAVELLER_PASSWORD,
    role: 'traveler',
    phone: '9876543210',
  },
];
const missing = ['SEED_ADMIN_PASSWORD', 'SEED_TRAVELLER_PASSWORD'].filter((k) => !process.env[k]);
if (missing.length) {
  console.error(`Set ${missing.join(' and ')} in server/.env before seeding (see .env.example).`);
  process.exit(1);
}

const SEED_DAYS = Number(process.env.SEED_DAYS) || 60;

// Each of the 52 manager accounts has its own random password, kept in a git-ignored file next to
// .env. Re-seeding reuses the passwords already in that file so existing logins keep working.
const CREDENTIALS_FILE = path.join(path.dirname(fileURLToPath(import.meta.url)), '..', 'manager-credentials.local.md');

function readCredentials() {
  if (!fs.existsSync(CREDENTIALS_FILE)) return {};
  const rows = fs.readFileSync(CREDENTIALS_FILE, 'utf8').matchAll(/^\| ([^|]+?@atlas\.test) \| `([^`]+)` \|/gm);
  return Object.fromEntries([...rows].map(([, email, password]) => [email, password]));
}

function newPassword() {
  // 16 URL-safe characters, always containing a letter and a digit (the sign-up rule).
  return `${crypto.randomBytes(12).toString('base64url').slice(0, 14)}a${crypto.randomInt(10)}`;
}

function writeCredentials(managers) {
  const lines = [
    '# Atlas manager accounts — LOCAL ONLY, never commit or share',
    '',
    'Generated by `npm run seed`. Re-seeding keeps these passwords. Delete this file and re-seed to rotate them all.',
    '',
    '| Email | Password | Role | Supplier |',
    '|---|---|---|---|',
    ...managers.map((m) => `| ${m.email} | \`${m.password}\` | ${m.role} | ${m.supplierName} |`),
    '',
  ];
  fs.writeFileSync(CREDENTIALS_FILE, lines.join('\n'), { mode: 0o600 });
}

async function insertInChunks(Model, docs, size = 500) {
  for (let i = 0; i < docs.length; i += size) {
    await Model.insertMany(docs.slice(i, i + size), { ordered: false });
  }
}

async function main() {
  await connectDb(process.env.MONGODB_URI);
  console.time('seed');

  const airlineSuppliers = generateAirlineSuppliers();
  const hotels = generateHotels();
  const hotelSuppliers = generateHotelSuppliers(hotels);
  hotelSuppliers.forEach((supplier, i) => {
    hotels[i].supplierId = supplier._id;
  });
  const services = generateServices({ airlineSuppliers });
  const reviews = generateReviews(services, hotels); // sets service and hotel ratings first…
  const flights = generateDepartures(services, { days: SEED_DAYS }); // …so departures copy them

  const offers = generateOffers({ suppliers: [...airlineSuppliers, ...hotelSuppliers] });

  const models = [Supplier, Service, Flight, Hotel, Review, Booking, Payment, Notification, AuditLog, Offer, Ticket, CancellationTemplate, Config, Photo, Statement, Adjustment, Event, DailyStat];
  await Promise.all(models.map((Model) => Model.deleteMany({})));
  await mongoose.connection.db.dropCollection('coupons').catch(() => {}); // Phase 1 stub, replaced by offers
  await Promise.all([...models, User].map((Model) => Model.syncIndexes()));

  await insertInChunks(Supplier, [...airlineSuppliers, ...hotelSuppliers]);
  await insertInChunks(Service, services);
  await insertInChunks(Flight, flights);
  await insertInChunks(Hotel, hotels);
  await insertInChunks(Review, reviews, 1000);
  await insertInChunks(Offer, offers);
  await CancellationTemplate.insertMany(DEFAULT_TEMPLATES);
  await Config.create({ key: 'commissionRate', value: DEFAULT_COMMISSION_RATE });

  for (const { password, ...user } of DEMO_USERS) {
    await User.updateOne({ email: user.email }, { $set: { ...user, passwordHash: await bcrypt.hash(password, 10) } }, { upsert: true });
  }

  const saved = readCredentials();
  const managers = [...airlineSuppliers, ...hotelSuppliers].map((supplier) => {
    const email = `${supplier.slug}@atlas.test`;
    return {
      email,
      name: `${supplier.name} manager`,
      role: supplier.kind === 'airline' ? 'airline_manager' : 'hotel_manager',
      supplierId: supplier._id,
      supplierName: supplier.name,
      password: saved[email] || newPassword(),
    };
  });
  // Managers from an older seed whose supplier no longer exists would point at nothing.
  await User.deleteMany({ role: { $in: ['airline_manager', 'hotel_manager'] }, email: { $nin: managers.map((m) => m.email) } });
  for (const { password, supplierName: _supplierName, ...manager } of managers) {
    await User.updateOne({ email: manager.email }, { $set: { ...manager, passwordHash: await bcrypt.hash(password, 10) } }, { upsert: true });
  }
  writeCredentials(managers);

  // Six months of synthetic history: past trips, payments, funnel summaries, then the monthly statements.
  const history = generateHistory({
    airlineSuppliers,
    hotelSuppliers,
    services,
    hotels,
    offers,
    templates: Object.fromEntries(DEFAULT_TEMPLATES.map((t) => [t.key, t])),
  });
  await User.deleteMany({ email: new RegExp(`@${HISTORY_EMAIL_DOMAIN.replace(/\./g, '\\.')}$`) });
  await insertInChunks(User, history.users);
  // Keep the historical createdAt (Mongoose would otherwise stamp "now").
  for (let i = 0; i < history.bookings.length; i += 500) await Booking.insertMany(history.bookings.slice(i, i + 500), { ordered: false, timestamps: false });
  await insertInChunks(Payment, history.payments);
  await insertInChunks(DailyStat, history.dailyStats);
  for (const [offerId, used] of Object.entries(history.offerUse)) {
    const offer = offers.find((o) => String(o._id) === offerId);
    if (offer.status !== 'exhausted') await Offer.updateOne({ _id: offerId }, { $inc: { redemptions: used } });
  }
  const settlement = await seedSettlementHistory({ Statement, Ticket, Adjustment, closeStatements, istPeriod, periodStart, shiftPeriod, periodLabel });

  console.log(
    `Seeded ${airlineSuppliers.length + hotelSuppliers.length} suppliers, ${services.length} services, ` +
      `${flights.length} departures (${SEED_DAYS} days), ${hotels.length} hotels, ${reviews.length} reviews, ${offers.length} offers.`,
  );
  console.log(`History: ${history.bookings.length} past bookings, ${history.payments.length} payments, ${settlement.statements} statements over ${settlement.periods} months.`);
  console.log(`Accounts: ${DEMO_USERS.map((u) => `${u.email} (${u.role})`).join(', ')} — passwords are the SEED_* values in server/.env`);
  console.log(`${managers.length} manager accounts — passwords in server/manager-credentials.local.md (git-ignored)`);
  console.timeEnd('seed');
}

main()
  .catch((err) => {
    console.error(err);
    process.exitCode = 1;
  })
  .finally(() => mongoose.disconnect());
