// Seeded offers (spec Appendix D): a fixed set, none random. Evergreen offers get rolling windows
// relative to the seed date; festive offers use the real 2026–2027 festival dates (services/calendar.js)
// with booking-date windows that open about two weeks before each festival.
import mongoose from 'mongoose';
import { addDays, todayIstString } from '../utils/dates.js';

// Offer artwork is themed (festivals, cabins, luggage), never a city or hotel photo, so an offer can't be
// mistaken for a destination or a property (client/public/images/seed/offers).
const art = (name) => `/images/seed/offers/${name}.jpg`;

export function generateOffers({ suppliers, today = todayIstString() }) {
  const byName = Object.fromEntries(suppliers.map((s) => [s.name, s]));
  const platform = (o) => ({ funder: 'platform', supplierId: null, supplierName: null, ...o });
  const supplier = (name, o) => ({ funder: 'supplier', supplierId: byName[name]._id, supplierName: name, ...o });
  const festive = (slug, title, summary, image, value, maxDiscount, validFrom, validTo) =>
    platform({ slug, title, summary, image, auto: true, code: null, scope: 'both', discountType: 'percent', value, maxDiscount, minSpend: 3000, validFrom, validTo });

  const offers = [
    platform({
      slug: 'welcome-to-atlas',
      code: 'WELCOME10',
      title: 'Welcome to Atlas',
      summary: '10% off your first three bookings, up to ₹1,500',
      description: 'A small thank-you for trying Atlas: 10% off the base fare or room charges on each of your first three bookings.',
      image: art('welcome'),
      scope: 'both',
      discountType: 'percent',
      value: 10,
      maxDiscount: 1500,
      minSpend: 2000,
      firstBookingsOnly: true,
      validFrom: addDays(today, -7),
      validTo: addDays(today, 180),
    }),
    platform({
      slug: 'fly-for-less',
      code: 'FLY500',
      title: 'Fly for less',
      summary: '₹500 off flights over ₹4,000',
      description: 'A flat ₹500 off the base fare of any flight on Atlas when the fare comes to ₹4,000 or more.',
      image: art('plane-sky'),
      scope: 'flights',
      discountType: 'flat',
      value: 500,
      minSpend: 4000,
      validFrom: addDays(today, -3),
      validTo: addDays(today, 45),
    }),
    festive('navratri-getaways-2026', 'Navratri getaways', '8% off flights and stays during Navratri, up to ₹1,200', art('marigold'), 8, 1200, '2026-09-27', '2026-10-21'),
    festive('diwali-journeys-2026', 'Diwali journeys', '12% off trips home for Diwali, up to ₹2,000', art('diya'), 12, 2000, '2026-10-22', '2026-11-11'),
    festive('sankranti-pongal-2027', 'Sankranti & Pongal', '8% off for the harvest festivals, up to ₹1,000', art('kites'), 8, 1000, '2026-12-30', '2027-01-17'),
    festive('holi-2027', 'Holi weekend', '10% off for Holi, up to ₹1,200', art('holi-colours'), 10, 1200, '2027-03-07', '2027-03-24'),
    festive('navratri-getaways-2027', 'Navratri getaways', '8% off flights and stays during Navratri, up to ₹1,200', art('marigold'), 8, 1200, '2027-09-15', '2027-10-10'),
    festive('diwali-journeys-2027', 'Diwali journeys', '12% off trips home for Diwali, up to ₹2,000', art('diya'), 12, 2000, '2027-10-11', '2027-11-01'),
    supplier('IndiGo', {
      slug: 'indigo-weekender',
      code: '6EWEEKEND',
      title: 'IndiGo weekender',
      summary: '7% off IndiGo flights, up to ₹800',
      description: 'Funded by IndiGo: 7% off the base fare on any IndiGo flight.',
      image: art('wing-sunset'),
      scope: 'flights',
      discountType: 'percent',
      value: 7,
      maxDiscount: 800,
      minSpend: 2500,
      validFrom: addDays(today, -2),
      validTo: addDays(today, 30),
    }),
    supplier('Air India', {
      slug: 'air-india-business-class',
      code: 'AIBIZ',
      title: 'Air India business for less',
      summary: '₹2,500 off Air India business fares over ₹15,000',
      description: 'Funded by Air India: a flat ₹2,500 off business fares of ₹15,000 or more.',
      image: art('business-cabin'),
      scope: 'flights',
      discountType: 'flat',
      value: 2500,
      minSpend: 15000,
      redemptionLimit: 200,
      validFrom: addDays(today, -5),
      validTo: addDays(today, 40),
    }),
    supplier('The Marine Palm', {
      slug: 'monsoon-at-the-marine-palm',
      code: 'MARINEPALM',
      title: 'Sea views for less',
      summary: '15% off stays at The Marine Palm, up to ₹3,000',
      description: 'Funded by The Marine Palm: 15% off the room charges of any stay.',
      image: art('breakfast-tray'),
      scope: 'hotels',
      discountType: 'percent',
      value: 15,
      maxDiscount: 3000,
      validFrom: addDays(today, -1),
      validTo: addDays(today, 50),
    }),
    supplier('The Lodhi Courtyard', {
      slug: 'lodhi-long-stays',
      auto: true,
      code: null,
      title: 'Longer stays at The Lodhi Courtyard',
      summary: '₹1,500 off stays over ₹15,000, applied automatically',
      description: 'Funded by The Lodhi Courtyard: ₹1,500 off the room charges when they come to ₹15,000 or more.',
      image: art('room-keys'),
      scope: 'hotels',
      discountType: 'flat',
      value: 1500,
      minSpend: 15000,
      validFrom: addDays(today, -10),
      validTo: addDays(today, 60),
    }),
    platform({
      slug: 'summer-sale-ended',
      code: 'SUMMER15',
      title: 'Summer sale',
      summary: '15% off, up to ₹1,000 (this offer has ended)',
      image: art('summer-kit'),
      scope: 'both',
      discountType: 'percent',
      value: 15,
      maxDiscount: 1000,
      validFrom: addDays(today, -120),
      validTo: addDays(today, -30),
      status: 'expired',
      endNotified: true,
    }),
    platform({
      slug: 'flash-fifty',
      code: 'FIRST50',
      title: 'The first fifty',
      summary: '₹750 off for the first 50 bookings (fully used)',
      image: art('gift'),
      scope: 'both',
      discountType: 'flat',
      value: 750,
      minSpend: 3000,
      redemptionLimit: 50,
      redemptions: 50,
      validFrom: addDays(today, -20),
      validTo: addDays(today, 20),
      status: 'exhausted',
      endNotified: true,
    }),
  ];

  return offers.map((o) => ({
    _id: new mongoose.Types.ObjectId(),
    auto: false,
    description: '',
    maxDiscount: null,
    minSpend: 0,
    redemptionLimit: null,
    redemptions: 0,
    firstBookingsOnly: false,
    status: o.validTo < today ? 'expired' : 'active',
    ...o,
  }));
}
